fixed compilation of sql/server/rel_dump.c --- hopefully correctly:
fixed

sql/server/rel_dump.c: In function 'exp_read':
sql/server/rel_dump.c:693:16: error: 'cname' may be used uninitialized in this function

by initializing 'cname' to NULL,
hoping that this is the correct default value,
and the uninitialized use was/is not due to unintended
use of 'cname' ...