Fix compilation error: dev/monetdb5/extras/rapi/rapi.c:589:3: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
Enter commit message.  Lines beginning with 'HG:' are removed.