Bug fix: [ monetdb-Bugs-1475675 ] PF: all but one XQuery-RPC test fail
Without "ADDHELP", the proc "get_rpc_res" is not listed in
sigs("xquery_rpc").  This was probably the reason that causes the
XQuery-RPC tests fail with the message:

    ERROR: interpret: no matching MIL operator to
    'get_rpc_res(BAT[oid,BAT], oid, str, BAT[oid,lng],
    BAT[oid,dbl], BAT[oid,dbl], BAT[oid,str])'.

With an "ADDHELP", this bug seems fixed.