fixing code to make it compile (also) with Intel's icc:
crackers_pq.h(5): error #1782: #pragma once is obsolete. Use #ifndef guard instead.
  #pragma once
              ^

Removed "#pragma once"; multiple inclusion of header file was already prevented
by #ifndef guard.


crackers_pq.h(14): error #344: typedef name has already been declared (with same type)
  typedef unsigned long ulong; /* instead of size_t */
                        ^

Removed redundant type (re-)definition.