fixed compilation with icc:
avoid
"
.../clients/src/mapilib/Mapi.mx(2342): error #592: variable "s" is used before its value is set
  		struct sockaddr_un s; /* just for sizeof(s.sun_path) */ (void)s;
  		                                                              ^
"
and
"
.../sql/src/backends/monet5/merovingian/merovingian_forkmserver.c(279): error #592: variable "s" is used before its value is set
  			struct sockaddr_un s; /* only for sizeof(s.sun_path) :( */ (void)s;
  			                                                                 ^
"
by removing non-required "(void)s;"

No "fake use" is required, as the variable is actually used in the sizeof()
statement.