fixed compilation with assertions disabled: pathfinder/compiler/algebra-m5sql/msa.c:190: error: "expr_cols_in_schema" defined but not used
Function expr_cols_in_schema() is only used when assertions are enabled,
i.e., when NDEBUG is not defined;
hence, we better also define the function itself only in case
assertions are enabled, i.e., NDEBUG is not defined.