removed set but unused variable "p" to fixed compilation with Intel icc:
sql/backends/monet5/rel_bin.c(540): error #593: variable "p" was set but never used
  prop *p;
        ^