backout changeset 93f7af3603b8, it breaks compilation
On Fedora 16 (sofia):

/usr/include/bits/fcntl2.h:45:26: error: call to ‘__open_too_many_args’
declared with attribute error: open can be called either with 2 or 3
arguments, not more

We probably should do a configure check for this to get it right.